# This is a build file for Travis CI.
# See: https://travis-ci.org/mbitsnbites/microS3

language: cpp

# Linux
os: linux
dist: xenial
compiler: gcc
addons:
  apt:
    packages:
      - ninja-build
env:
  - BUILD_SHARED=off
  - BUILD_SHARED=on
script:
  - mkdir out && cd out
  - cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=${BUILD_SHARED} ..
  - cmake --build .
  - CTEST_OUTPUT_ON_FAILURE=TRUE ctest

matrix:
  include:
    # macOS clang
    - os: osx
      compiler: clang
      osx_image: xcode10.2
      addons:
        homebrew:
          packages:
            - ninja
      script:
        - mkdir out && cd out
        - cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=off ..
        - cmake --build .
        - CTEST_OUTPUT_ON_FAILURE=TRUE ctest

    # Windows MinGW cross compile on Linux
    - os: linux
      dist: xenial
      compiler: mingw
      addons:
        apt:
          packages:
            - ninja-build
            - gcc-mingw-w64-x86-64
            - g++-mingw-w64-x86-64
      script:
        - mkdir out && cd out
        - CC=x86_64-w64-mingw32-gcc CXX=x86_64-w64-mingw32-g++ cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=off -DCMAKE_BUILD_WITH_INSTALL_RPATH=on ..
        - cmake --build .

    # Windows MSVC 2017
    - os: windows
      compiler: msvc
      env:
        - MATRIX_EVAL="CC=cl.exe && CXX=cl.exe"
      before_install:
        - eval "${MATRIX_EVAL}"
      install:
        - choco install ninja
      script:
        - mkdir out && cd out
        - cmd.exe /C '"C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvarsall.bat" amd64 &&
          cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=off .. &&
          ninja'
        - CTEST_OUTPUT_ON_FAILURE=TRUE ninja test
